---
title: "Caso 9. Arbol de Clasificación. Daños corazón. Programación Python"
author: "Rubén Pizarro Gurrola"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 6
    number_sections: yes
bibliography: references.bib
---

# Objetivo

Implementar el modelo de árbol de clasificación con datos relacionados a una condición de salud de las personas para predecir anomalías de corazón y evaluar la exactitud del modelo mediante la matriz de confusión.

# Descripción

Se cargan librerías y se descargan los datos: <https://raw.githubusercontent.com/rpizarrog/Analisis-Inteligente-de-datos/main/datos/heart_2020_cleaned.csv>

Los datos están relacionados con aspectos médicos y son valores numéricos de varias variables que caracterizan el estado de salud de 319,795 personas.

Se construye un modelo supervisado basado en el algoritmo de árbol de clasificación para resolver la tarea de clasificación binaria e identificar si una persona padece del corazón o no.

Se construyen datos de entrenamiento y validación al 80% y 20% cada uno.

Se desarrollan los modelos en Python de:

-   Regresión Logística binaria

-   **Árbol de Clasificación tipo class**

-   K Means

-   SVM Lineal

-   SVM Polinomial

-   SVM Radial

Los modelo se aceptan si tienen un valor de exactitud (accuracy) por encima del 70%..

# Fundamento teórico

Los árboles de clasificación son el subtipo de árboles de predicción que se aplica cuando la variable respuesta dependiente es de tipo categórica o cualitativa y que tiene un significado conforme o de acuerdo a una etiqueta.[@amat_rodrigo_arboles_2017]

[@amat_rodrigo_arboles_2020]

La etiqueta puede ser 'BUENO' o 'MALO'; '0' o '1'; 'ALTO' O 'BAJO'; 'ENFERMO, 'NO ENFERMO'; entre otros ejemplos.

# Desarrollo

## Cargar librerías

Algunas librerías son nuevas, hay que instalarlas desde R, aquí se indican cuáles librerías y con comentario dado que ya se instalaron previamente.

```{r}
# library(reticulate)
# py_install("statsmodels")
```

```{python}
# Tratamiento de datos
import pandas as pd
import numpy as np
import statsmodels.api as sm

# Estadísticas
import scipy 
from scipy import stats

# Para partir datos entrenamiento y validación
from sklearn.model_selection import train_test_split

# Modelo de Clasificación 
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.tree import export_graphviz
from sklearn.tree import export_text
from sklearn.model_selection import GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Gráficos
import matplotlib.pyplot as plt
import seaborn as sb


```

## Cargar los datos

Se cargan datos del enlace *URL*, se observan los primeros y últimos registros del conjunto de datos.

```{python}
datos = pd.read_csv("https://raw.githubusercontent.com/rpizarrog/Analisis-Inteligente-de-datos/main/datos/heart_2020_cleaned.csv")
datos
```

## Exploración de datos

Son 319795 observaciones y 18 variables

```{python}
print("Observaciones y variables: ", datos.shape)
print("Columnas y tipo de dato")
# datos.columns
datos.dtypes
```

### Visualización de datos

#### ¿Cuántos casos hay de cada clase?

Hay 292422 casos sin daño al corazón y el resto que si tienen daño 27373.

```{python}
frecuencia = (datos.groupby("HeartDisease").agg(frecuencia=("HeartDisease","count")).reset_index())
  
frecuencia
```

```{python}


fig, ax = plt.subplots()
# Colores
bar_labels = ['No', 'Yes']
bar_colors = ['tab:blue', 'tab:red']

#frecuencia['frecuencia'].plot(kind="bar")
ax.bar(frecuencia['HeartDisease'], frecuencia['frecuencia'], label=bar_labels, color=bar_colors)

ax.set_ylabel('Frecuencia')
ax.set_title('Daños al Corazón')
ax.legend(title='Daño')

plt.show()
# plt.gcf().clear()

```

#### Histogramas de datos numéricos

Histograma únicamente de las variables numéricas del conjunto de datos *'BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'.*

```{python}
datos[['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime']].hist()

```

## Transformar datos

Crear variable llamada *HeartDisease01* que se utilizará en el modelo de **Regresión Logística** tendrá valores **0** de para 'No' daño y **1** para si hay daño ('*Yes*').

```{python}
datos['HeartDisease01'] = np.where(datos ['HeartDisease']== "Yes", 1, 0)
 
```

Quitar la variable HeartDisease que ya tiene variable transformada a HeartDisease01

```{python}
datos = datos.drop("HeartDisease", axis='columns')
```

Quedaron las columnas:

```{python}
datos.columns.values
```

### Las variables de interés

Todas las variables de entrada o variables independientes:

-   "*BMI*": Indice de masa corporal con valores entre 12.02 y 94.85.

-   "*Smoking*": Si la persona es fumadora o no con valores categóritos de 'Yes' o 'No'.

-   "*AlcoholDrinking*" : Si consume alcohol o no, con valores categóricos de 'Yes' o 'No'.

-   "*Stroke*": Si padece alguna anomalía cerebrovascular, apoplejia o algo similar, con valores categóricos de 'Yes' o 'No'.

-   "*PhysicalHealth*" Estado físico en lo general con valores entre 0 y 30.

-   "*MentalHealth*". Estado mental en lo general con valores entre 0 y 30.

-   "*DiffWalking*" . Que si se le dificulta caminar o tiene algún padecimiento al caminar, con valores categóritoc de 'Yes' o 'No'.

-   "*Sex*": Género de la persona, con valores de 'Female' y 'Male' para distinguir al género femenino y masculino respectivamente.

-   "*AgeCategory*": Una clasificación de la edad de la persona de entre 18 y 80 años. La primera categoría con un rango de edad entre 18-24, a partir de 25 con rangos de 5 en 5 hasta la clase de 75-80 y una última categoría mayores de 80 años.

-   "*Race*". Raza u origen de la persona con valores categóricos de '*American Indian/Alaskan Native', 'Asian','Black', 'Hispanic', 'Other'* y'*White'.*

-   "*Diabetic*". Si padece o ha padecido de diabetes en cuatro condiciones siendo Yes y No para si o no: 'No', 'borderline diabetes' condición antes de detectarse diabetes tipo 2, 'Yes', y 'Yes (during pregnancy)' durante embarazo.

-   "*PhysicalActivity*" que si realiza actividad física, con valores categóricos de 'Yes' o 'No'.

-   "*GenHealth*": EStado general de salud de la persona con valores categóricos de 'Excellent', 'Very good', 'Good', 'Fair' y 'Poor' con significado en español de excelente, muy buena, buena, regular y pobre o deficiente.

-   "*SleepTime*": valor numérico de las horas de sueño u horas que duerme la persona con valores en un rango entre 1 y 24.

-   "*Asthma*": si padece de asma o no, con valores categóricos de 'Yes' o 'No'.

-   "*KidneyDisease*": si tiene algún padecimiento en los riñones, con valores categóricos de 'Yes' o 'No'.

-   "*SkinCancer*": si padece algún tipo de cáncer de piel, con valores categóricos de 'Yes' o 'No'.

La variable de interés como dependiente o variable de salida es la de daño al corazón (*HeartDisease*), con valores categóricos de 'Yes' o 'No' , ahora la variable *HeartDisease01* con valores *'1' o '0'.*

Nuevamente la descripción de variables y ahora son 319795 observaciones y 18 variables

```{python}
print("Observaciones y variables: ", datos.shape)
print("Columnas y tipo de dato")
# datos.columns
datos.dtypes
```

Para construir el modelo, se requiere variables de tipo numérica, aún se tienen en las variables independiente variables de tipo categóricas u *object* en *Python*:

Las variables que son categóricas: *'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex', 'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'Asthma', 'KidneyDisease', 'SkinCancer'*.

Con estas variables, crear variables *Dummys* y construir un conjunto de datos que incluye las variable dummis.

El método de la librería de Pandas llamado *get_dummies()* convierte los datos categóricos en variables indicadoras o ficticias.

```{python}
datos_dummis = pd.get_dummies(datos, drop_first = True)
datos_dummis
```

Asi queda el conjunto de datos preparado llamado *datos_dummis*

```{python}
datos_dummis.dtypes
```

## Datos de entrenamiento y validación

Datos de entrenamiento al 80% de los datos y 20% los datos de validación. Semilla 2022

```{python}
X_entrena, X_valida, Y_entrena, Y_valida = train_test_split(datos_dummis.drop(columns = "HeartDisease01"), datos_dummis['HeartDisease01'],train_size = 0.80,  random_state = 2022)
```

### Datos de entrenamiento

Se crea un conjunto de datos de validación con 255836 registros y 37 variables.

```{python}
X_entrena
```

### Datos de validación

Se crea un conjunto de datos de validación con 63959 registros y 37 variables.

```{python}
X_valida
```

## Modelos Supervisados de Arbol de Clasificación

### Creación del modelo

Se crea el modelo de árbol de clasificación con datos de entrenamiento

```{python}
modelo_ac = DecisionTreeClassifier(
            max_depth         = 5,
            criterion         = 'gini',
            random_state      = 2022
          )
```

```{python}
modelo_ac.fit(X_entrena, Y_entrena)
```

### Visualización del árbol

```{python}
fig, ax = plt.subplots(figsize=(13, 6))

print(f"Profundidad del árbol: {modelo_ac.get_depth()}")
print(f"Número de nodos terminales: {modelo_ac.get_n_leaves()}")

plot = plot_tree(
            decision_tree = modelo_ac,
            #feature_names = modelo_ac.tolist(),
            class_names   = 'Daño al corazón',
            filled        = True,
            impurity      = False,
            fontsize      = 7,
            ax            = ax
       )
```

### Reglas de asociación para la construcción del árbol

```{python}
texto_modelo = export_text(
                    decision_tree = modelo_ac,
                    feature_names = list(datos_dummis.drop(columns = "HeartDisease01").columns)
               )
print(texto_modelo)
```

## Prediccions

Se construyen predicciones con los datos de validación.

```{python}
predicciones = modelo_ac.predict(X_valida)
print(predicciones)
```

### Tabla comparativa

```{python}
comparaciones = pd.DataFrame(X_valida)
comparaciones = comparaciones.assign(HeartDisease_Real = Y_valida)
comparaciones = comparaciones.assign(HeartDisease_Pred = predicciones.flatten().tolist())
print(comparaciones)

```

### Evaluación del modelo

Se evalúa el modelo con la matriz de confusión

#### Matriz de confusión

```{python}
print(confusion_matrix(comparaciones['HeartDisease_Real'], comparaciones['HeartDisease_Pred']))

matriz = confusion_matrix(comparaciones['HeartDisease_Real'], comparaciones['HeartDisease_Pred'])

```

#### ¿A cuantos le atina el modelo?

```{python}
print(classification_report(comparaciones['HeartDisease_Real'], comparaciones['HeartDisease_Pred']))
```

```{python}
accuracy = accuracy_score(
    y_true = comparaciones['HeartDisease_Real'],
    y_pred = comparaciones['HeartDisease_Pred'],
    normalize = True
    )
print(f"El accuracy de test es: {100 * accuracy} %")

```

## Prediccions con un registro nuevo

Se crea un registro de una persona con ciertas condiciones de salud a partir de un diccionario.

```{python}
# Se crea un diccionario
registro = {'BMI': 38, 'PhysicalHealth': 2, 'MentalHealth': 5, 'SleepTime' : 12, 'Smoking_Yes' : 1, 'AlcoholDrinking_Yes' : 1, 'Stroke_Yes' : 1, 'DiffWalking_Yes': 1, 'Sex_Male': 1, 
'AgeCategory_25-29' : 0, 'AgeCategory_30-34' : 0, 
'AgeCategory_35-39' : 0, 'AgeCategory_40-44' : 0, 
'AgeCategory_45-49' : 0, 'AgeCategory_50-54' : 0,
'AgeCategory_55-59' : 0, 'AgeCategory_60-64' : 0,
'AgeCategory_65-69' : 0, 'AgeCategory_70-74': 1, 
'AgeCategory_75-79' : 0, 'AgeCategory_80 or older' : 0,         'Race_Asian' : 0, 'Race_Black' : 1, 'Race_Hispanic' : 0,
'Race_Other' : 0, 'Race_White' : 0,
'Diabetic_No, borderline diabetes' : 0, 'Diabetic_Yes' : 1,
'Diabetic_Yes (during pregnancy)' : 0, 
'PhysicalActivity_Yes' : 0, 'GenHealth_Fair' : 1, 
'GenHealth_Good' : 0, 'GenHealth_Poor' : 0, 
'GenHealth_Very good' : 0, 'Asthma_Yes' : 1, 'KidneyDisease_Yes':1, 'SkinCancer_Yes': 0}
persona = pd.DataFrame()
persona = persona.append(registro, ignore_index=True)
persona
```

Se hace la predicción en términos de clasificación de la persona con estos valores para saber si tiene o no daño en el corazón:

```{python}
prediccion = modelo_ac.predict(persona)
print(prediccion)
```

La predicción en términos de clasificación de la persona con las características proporcionadas es que está enfermo o tiene daño del corazón.

# Interpretación

Se hace una evaluación del modelo de regresión logística basada en el estadístico de *accuracy* de la matriz de confusión.

Habiendo realizado predicciones con los datos de validación, se tiene un valor de aproximadamente del $91.68 \%$ aproximadamente el 92% de exactitud en el modelo de árbol de regresión.

El modelo se aprueba dado que la métrica era igual o superior del $70%$.

Habrá que compararlo contra otro modelo de clasificación.

Se hizo una predicción de un caso e una persona con ciertas condiciones de salud y la predicción en términos de clasificación resulta que ésta persona tiene daño al corazón.

¡El modelo es bueno!,

# Bibliografía
