---
title: "Caso 8. Regresión Logística Binaria. Predicciones de daño corazón. Python"
author: "Rubén Pizarro Gurrola"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 6
    number_sections: yes
bibliography: references.bib
---

# Objetivo

Implementar el modelo de regresión logística binaria con datos relacionados a una condición de salud de las personas para predecir anomalías de corazón y evaluar la exactitud del modelo mediante la matriz de confusión.

# Descripción

Se cargan librerías y se descargan los datos: <https://raw.githubusercontent.com/rpizarrog/Analisis-Inteligente-de-datos/main/datos/heart_2020_cleaned.csv>

Los datos están relacionados con aspectos médicos y son valores numéricos de varias variables que caracterizan el estado de salud de 319,795 personas.

Se pretende construir un modelo utilizando **algoritmos supervisados** para resolver la **tarea de clasificación binaria** e identificar si una persona padece del corazón o no.

Se construyen datos de entrenamiento y validación al 80% y 20% cada uno.

Se desarrollan los modelos de:

-   **Regresión Logística binaria**

-   Árbol de Clasificación tipo class

-   K Means

-   SVM Lineal

-   SVM Polinomial

-   SVM Radial

Los modelo se aceptan si tienen un valor de exactitud ("*Accuracy*") por encima del 70%..

El modelo se construye con funciones de librerías de *python*

# Fundamento teórico

La regresión logística ofrece solución para clasificar y para predecir valores lógicos, es decir con un valor etiquetado tal vez 0 o 1; bueno o malo, alto o bajo, entre otras etiquetas que distingan una polaridad o significado dicotómico, o un valor u otro.

Para predicciones el modelo de regresión logística binaria encuentra la probabilidad de ocurrencia de un evento determinado y dicha probabilidad se hallará siempre dentro del rango.

Cuando la variable respuesta posee dos categorías, entonces se estará delante de una regresión logística binaria.

En cambio, si la variable respuesta posee más de dos categorías, se usará la regresión logística multinomial .

El resultado real de muchos algoritmos de clasificación binaria es una puntuación de predicción en términos de probabilidad. La probabilidad indica la posible del modelo de que la observación dada pertenezca a la clase positiva.

Para tomar la decisión sobre si la observación debe clasificarse como positiva o negativa, como interpretación de la probabilidad se define el umbral de clasificación o el corte que normalmente es 50% arriba es positiva y 50% abajo es negativa y compara con la puntuación con dicho umbral de la predicción.

Cualquier observación con puntuaciones superiores al umbral se prevé como la clase positiva y las puntuaciones inferiores al umbral se prevén como la clase negativa.[@amazonmahinelearning].

En este caso que se presenta y describe a continuación, se utiliza la regresión logística binomial como parte de los algoritmos supervisados de machine learning.

El modelo requiere una cantidad de variables independientes del modelo $x_1, x_2 ... x_n$ ó $\beta_1, \beta_2...\beta_n$.

Se debe identificar la variable dependiente $Y$ o la variable respuesta de tipo binaria, donde cada componente de 𝑌 se distribuye mediante una distribución de Bernoulli $[ 0 | 1]$.

Se necesitan $𝑛$ el número de observaciones.

Entonces $𝑋 = (𝑥_1, … , 𝑥_𝑛)^T$ el conjunto de variable independientes.

Se identifica como $\theta$ el vector de parámetros asociado al modelo, de forma que $\theta\in R^{k+1}$ que significa que los valores del vector resultante pertenecen a cada una de las variables.

Sea $\pi(\theta^T𝑥_𝑖)$ la probabilidad de que $Y_i$ tome un valor igual a $1$, entonces su modelo se puede escribir como:

$$
\pi(\theta^Tx_i) = P(Y =1|X=x) = \frac{1}{1+e}
$$

Si $\theta^Tx_i$ los valores ajustados toma valores elevados y positivos, entonces ... ... se aproximará a 0 y, en consecuencia, el valor de la función anterior será igual a 1. En caso de que $\theta^Tx_i$ tome valores elevados pero negativos, entonces el valor de la función será $0$ dado que $e ^ {\theta^Tx_i}$ tenderá a infinito. [@zang2020].

El valor $e$ como número irracional y basado en la teoría de logaritmos naturales es el valor constante que se puede obtener en lenguaje R con la función exp(1) igual a r exp(1).

Efectuando la transformación logit a la expresión inicial, se obtiene:

$$
logit(\pi(\theta^Tx_i)) = ln(\frac{\pi(\theta^Tx_i)}{1 - \pi(\theta^Tx_i)})
$$

que significa calcular el logaritmo natural de cada valor de de $x_i$ para determinar su probabilidad.

# Desarrollo

## Cargar librerías

Librería nueva que hay que nstalar:

-   py_install("plotnine") \# desde R es para gráficos *ggplot en caso de usarse*

-   *py_install("sidetable")* para tablas de frecuencias se usa en gráficos de barras

```{python}
# Tratamiento de datos
import pandas as pd
import numpy as np

# Estadísticas
import scipy
from scipy import stats

# Para partir datos entrenamiento y validación
from sklearn.model_selection import train_test_split

# Modelo de Clasificación 
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Gráficos
import matplotlib.pyplot as plt
import seaborn as sb

# Graficos ggplot similar a R
from plotnine import *  # Antes instalar > py_install("plotnine") desde R o Python

# tablas de frecuencias
import sidetable as stb

```

## Cargar datos

Se cargan datos del enlace *URL*, se observan los primeros y últimos registros del conjunto de datos.

```{python}
datos = pd.read_csv("https://raw.githubusercontent.com/rpizarrog/Analisis-Inteligente-de-datos/main/datos/heart_2020_cleaned.csv")
datos
```

## Exploración de datos

Son 319795 observaciones y 18 variables

```{python}
print("Observaciones y variables: ", datos.shape)
print("Columnas y tipo de dato")
# datos.columns
datos.dtypes
```

### Visualización de datos

#### ¿Cuántos casos hay de cada clase?

Hay 292422 casos sin daño al corazón y el resto que si tienen daño 27373.

```{python}
frecuencia = (datos.groupby("HeartDisease").agg(frecuencia=("HeartDisease","count")).reset_index())
  
frecuencia
```

```{python}


fig, ax = plt.subplots()
# Colores
bar_labels = ['No', 'Yes']
bar_colors = ['tab:blue', 'tab:red']

#frecuencia['frecuencia'].plot(kind="bar")
ax.bar(frecuencia['HeartDisease'], frecuencia['frecuencia'], label=bar_labels, color=bar_colors)

ax.set_ylabel('Frecuencia')
ax.set_title('Daños al Corazón')
ax.legend(title='Daño')

plt.show()
# plt.gcf().clear()

```

#### Histogramas de datos numéricos

Histograma únicamente de las variables numéricas del conjunto de datos *'BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'.*

```{python}
datos[['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime']].hist()

```

#### Diagramas de frecuencias de datos categóricos

Diagramas de frecuencias con barras de las variables categóricas: 'Smoking', 'AlcoholDrinking', 'Stroke', ...,.

```{python}
frecuencia = (datos.groupby("Smoking").agg(frecuencia=("Smoking", "count")).reset_index())

fig, ax = plt.subplots()
# Colores
bar_labels = ['No', 'Yes']
bar_colors = ['tab:blue', 'tab:red']

#frecuencia['frecuencia'].plot(kind="bar")
ax.bar(frecuencia['Smoking'], frecuencia['frecuencia'], label=bar_labels, color=bar_colors)

ax.set_ylabel('Frecuencia')
ax.set_title('Fumador')
ax.legend(title='Daño')

# plt.show()
# plt.gcf().clear()
  
  

```

## Transformar datos

Crear variable llamada *HeartDisease01* que se utilizará en el modelo de **Regresión Logística** tendrá valores **0** de para 'No' daño y **1** para si hay daño ('*Yes*').

```{python}
datos['HeartDisease01'] = np.where(datos ['HeartDisease']== "Yes", 1, 0)
 
```

Quitar la variable HeartDisease que ya tiene variable transformada a HeartDisease01

```{python}
datos = datos.drop("HeartDisease", axis='columns')
```

Quedaron las columnas:

```{python}
datos.columns.values
```

### Las variables de interés

Todas las variables de entrada o variables independientes:

-   "*BMI*": Indice de masa corporal con valores entre 12.02 y 94.85.

-   "*Smoking*": Si la persona es fumadora o no con valores categóritos de 'Yes' o 'No'.

-   "*AlcoholDrinking*" : Si consume alcohol o no, con valores categóricos de 'Yes' o 'No'.

-   "*Stroke*": Si padece alguna anomalía cerebrovascular, apoplejia o algo similar, con valores categóricos de 'Yes' o 'No'.

-   "*PhysicalHealth*" Estado físico en lo general con valores entre 0 y 30.

-   "*MentalHealth*". Estado mental en lo general con valores entre 0 y 30.

-   "*DiffWalking*" . Que si se le dificulta caminar o tiene algún padecimiento al caminar, con valores categóritoc de 'Yes' o 'No'.

-   "*Sex*": Género de la persona, con valores de 'Female' y 'Male' para distinguir al género femenino y masculino respectivamente.

-   "*AgeCategory*": Una clasificación de la edad de la persona de entre 18 y 80 años. La primera categoría con un rango de edad entre 18-24, a partir de 25 con rangos de 5 en 5 hasta la clase de 75-80 y una última categoría mayores de 80 años.

-   "*Race*". Raza u origen de la persona con valores categóricos de '*American Indian/Alaskan Native', 'Asian','Black', 'Hispanic', 'Other'* y'*White'.*

-   "*Diabetic*". Si padece o ha padecido de diabetes en cuatro condiciones siendo Yes y No para si o no: 'No', 'borderline diabetes' condición antes de detectarse diabetes tipo 2, 'Yes', y 'Yes (during pregnancy)' durante embarazo.

-   "*PhysicalActivity*" que si realiza actividad física, con valores categóricos de 'Yes' o 'No'.

-   "*GenHealth*": EStado general de salud de la persona con valores categóricos de 'Excellent', 'Very good', 'Good', 'Fair' y 'Poor' con significado en español de excelente, muy buena, buena, regular y pobre o deficiente.

-   "*SleepTime*": valor numérico de las horas de sueño u horas que duerme la persona con valores en un rango entre 1 y 24.

-   "*Asthma*": si padece de asma o no, con valores categóricos de 'Yes' o 'No'.

-   "*KidneyDisease*": si tiene algún padecimiento en los riñones, con valores categóricos de 'Yes' o 'No'.

-   "*SkinCancer*": si padece algún tipo de cáncer de piel, con valores categóricos de 'Yes' o 'No'.

La variable de interés como dependiente o variable de salida es la de daño al corazón (*HeartDisease*), con valores categóricos de 'Yes' o 'No' , ahora la variable *HeartDisease01* con valores *'1' o '0'.*

Nuevamente la descripción de variables y ahora son 319795 observaciones y 18 variables

```{python}
print("Observaciones y variables: ", datos.shape)
print("Columnas y tipo de dato")
# datos.columns
datos.dtypes
```

### Construir variables Dummys

Existen variables que son categóricas: *'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex', 'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'Asthma', 'KidneyDisease', 'SkinCancer'*.

Con estas variables, crear variables *Dummys* y construir un conjunto de datos que incluye las variable dummis.

El método de la librería de Pandas llamado *get_dummies()* convierte los datos categóricos en variables indicadoras o ficticias.

```{python}
datos_dummis = pd.get_dummies(datos, drop_first = True)
datos_dummis
```

Asi queda el conjunto de datos preparado llamado *datos_dummis*

```{python}
datos_dummis.dtypes
```

## Datos de entrenamiento y validación

Datos de entrenamiento al 80% de los datos y 20% los datos de validación. Semilla 2022

```{python}
X_entrena, X_valida, Y_entrena, Y_valida = train_test_split(datos_dummis.drop(columns = "HeartDisease01"), datos_dummis['HeartDisease01'],train_size = 0.80,  random_state = 2022)
```

### Datos de entrenamiento

```{python}
X_entrena
```

### Datos de validación

```{python}
X_valida
```

## Modelos Supervisados de Clasificación

Se construye un modelo de regresión logística con los datos de entrenamiento y las variables independientes.

```{python}
modelo_rlog = linear_model.LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=1000)
modelo_rlog.fit(X_entrena, Y_entrena)
```

```{python}
print(modelo_rlog.score(X_entrena, Y_entrena))
```

### Predicciones

Se hacen predicciones con los datos de validación. Se observan las primeras 10.

```{python}
predicciones_rlog = modelo_rlog.predict(X_valida)
print(predicciones_rlog[0:10])
```

### Tabla comparativa

```{python}
comparaciones = pd.DataFrame(X_valida)
comparaciones = comparaciones.assign(HeartDisease_Real = Y_valida)
comparaciones = comparaciones.assign(HeartDisease_Pred = predicciones_rlog.flatten().tolist())
print(comparaciones)

```

### Evaluación del modelo

Se evalúa el modelo con la matriz de confusión

#### Matriz de confusión

```{python}
print(confusion_matrix(comparaciones['HeartDisease_Real'], comparaciones['HeartDisease_Pred']))


```

#### ¿A cuantos le atina el modelo?

```{python}
print(classification_report(comparaciones['HeartDisease_Real'], comparaciones['HeartDisease_Pred']))


```

### Predicciones con datos nuevos

Se crea un registro de una persona con ciertas condiciones de salud.

```{r}
BMI = 38
Smoking = 1 #'Yes'
AlcoholDrinking = 1 #'Yes'
Stroke = 1 #'Yes'
# PhysicalHealth = 2
# MentalHealth = 5
DiffWalking = 1 #'Yes'
# Sex = 'Male'
# AgeCategory = '70-74'
# Race = 'Black'
# Diabetic <- 'Yes'
# PhysicalActivity = "No"
# GenHealth = "Fair"
# SleepTime = 12
# Asthma = "Yes"
# KidneyDisease = "Yes"
# SkinCancer = 'No'
# persona = data.frame(BMI,Smoking, AlcoholDrinking, Stroke, PhysicalHealth, MentalHealth, DiffWalking, Sex, AgeCategory, Race, Diabetic, PhysicalActivity, GenHealth, SleepTime, Asthma, KidneyDisease, SkinCancer)
#persona
```

Se hace la predicción con estos valores de si tiene p no daño en el corazón:

### Interpretación

Se hace una evaluación del modelo de regresión logística basada en el estadístico de *accuracy* de la matriz de confusión.

Hhabiendo realizado predicciones con los datos de validación, se tiene un valor de aproximadamente del $92%$ con el de exactitud en el modelo de regresion logística .

El modelo se aprueba dado que la métrica era igual o superior del $70%$.

¡El modelo es bueno!

# Bibliografía
